### PR TITLE
Use Treeview on Activity copy

### PR DESCRIPTION
**Pull request by ibebic**
Screen Shot 2019-07-26 at 12 04 32

### CODE REVIEW

**Comment by ilijaveselica** [comment]
I would suggest removing left margin and reducing font size, it will be benefitial in cases when activities have 3 or more levels or activity titles are long

**Comment by ibebic** [comment]
> I would suggest removing left margin and reducing font size, it will be benefitial in cases when activities have 3 or more levels or activity titles are long

👍 Thanks for the suggestion, haven't thought of that. I decreased margins a bit, but instead of decreasing the font I increased the modal width for an additional 100px. It doesn't look too large even on smaller screens and the additional space is (I think) more than enough.

**Comment by underscope** [comment]
@ibebic Please update once #340 gets merged

**Comment by underscope** [comment]
Please merge latest develop and similar to the new creation dialog try to scope stuff you need for copying within copy dialog / store.

**Pull request merged**
