### PR TITLE
Remove bootstrap 🎉

### LINKED ISSUE #617: Remove bootstrap from the codebase

### PR DESCRIPTION
**Pull request by zcuric**
### This PR
- [x] removes bootstrap package
- [x] removes bootswatch package
- [x] removes loader.css package
- [x] removes jQuery
- [x] removes code related to bootstrap, bootswatch, loader.css
- [x] updates components to vuetify 

Closes #617

### CODE REVIEW

**Comment by zcuric** [comment]
@underscope removing bootstrap changes font. I can't find where the problem is.

**Comment by kjuej** [comment]
@zcuric Seems like the space between content is much larger than it was before. Is this intended?
Screen Shot 2020-08-27 at 14 13 54

**Comment by zcuric** [comment]
@kjuej nope, probably an issue.

**Comment by kjuej** [comment]
@zcuric able to add a question block to a saved assessment:
Screen Shot 2020-08-27 at 14 39 38

**Comment by zcuric** [comment]
@kjuej Can you check is this also on develop branch or it is introduced here?

**Comment by kjuej** [comment]
> @kjuej Can you check is this also on develop branch or it is introduced here?

Only on this branch.

**Comment by kjuej** [comment]
@zcuric Make collapsed assessments in assessment pool more visible:
Screen Shot 2020-08-27 at 14 42 13
Similar issue with assessment group (make border visible and reduce the space between assessments):
Screen Shot 2020-08-27 at 14 49 34

Develop comparison:
Screen Shot 2020-08-27 at 14 53 59
Screen Shot 2020-08-27 at 14 54 09

**Comment by kjuej** [comment]
@zcuric On develop branch i can change positions of assessments in assessment group (exam assessments only):
Screen Shot 2020-08-27 at 14 58 49

**Comment by underscope** [comment]
Hey @zcuric do you have plans/ETA for this one?

**Comment by zcuric** [comment]
@underscope currently busy with two projects, as soon as I get some free time, I'll tackle it. If you can find someone to jump in, that is also an option.

**Comment by underscope** [comment]
After giving it some thought I decided to close this one because of three reasons:
- I want to announce that we are completely dropping it for the next version so that teams have enough time to migrate their teaching elements which might be dependent on bootstrap
- I want them to be able to switch to v5 without spending too much time on it
- This is WIP and you don't have time at the moment

I created an issue for it, added it to the next milestone, and linked it here. I'll keep the branch so it can be revisited at some point.

Thanks!

**Pull request closed without merging**
