### PR TITLE
Discussion improvements

### PR DESCRIPTION
**Pull request by underscope**
- Migrate to vuetify
- Add email notifications

### CODE REVIEW

**Comment by kjuej** [comment]
@underscope Avatar icon not loaded correctly if it's shown in real time (with SSE).

Screen Shot 2019-11-27 at 12 19 48

**Comment by kjuej** [comment]
@underscope Would be more intuitive if a checkmark is added here to save the comment edit.

Screen Shot 2019-11-27 at 12 21 55

**Comment by kjuej** [comment]
@underscope Text overflow issue may occur.
Screen Shot 2019-11-27 at 12 56 28

**Comment by kjuej** [comment]
@underscope you can click submit twice before text is validated resulting in a double post:
Screen Shot 2019-11-27 at 12 56 28

**Comment by underscope** [comment]
@kjuej Please test tommorow on develop

**Pull request merged**
