### PR TITLE
Implement Jodit content element

### PR DESCRIPTION
**Pull request by vladimyr**
This PR introduces [`Jodit`](https://npm.im/jodit) powered rich text content element :tada:

image

### CODE REVIEW

**Comment by underscope** [comment]
@vladimyr Can we eliminate font size increase upon focus ?

**Comment by underscope** [comment]
Few additional suggestions:

- Eliminate inner border of focused element
- Eliminate font, font size and font style icons (similar to google docs)
- Show vertical dividers between control groups
- Make toolbar icons a bit larger
- Make toolbar controls a bit more condensed
- Move more commonly used actions to the left (i.e move sub/super script to far right)

**Comment by kjuej** [comment]
Minor issue: The image element is always initially inserted at the start of the editor.

**Comment by kjuej** [comment]
If an element is deeply nested, sometimes an overflow occurs. 
Screen Shot 2019-09-25 at 09 45 11

**Comment by kjuej** [comment]
I'm able to drag and drop other elements to the jodit element. (in which case the dragged element placeholder text gets copied to the jodit editor).
Screen Shot 2019-09-25 at 09 54 27

**Comment by abasic** [comment]
> Minor issue: The image element is always initially inserted at the start of the editor.

This is an issue with `Jodit` itself.

**Comment by kjuej** [comment]
Issue with editing a link after creating it(3/5 buttons for edit link functionality are not present after clicking a created link).

**Comment by zcuric** [comment]
Please merge the latest develop and run linter.

**Pull request closed without merging**
