### PR TITLE
Exam group time limit validation

### LINKED ISSUE #138: Able to set an exam group time limit to a negative number
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
Exam group time limit can be set to negative.

## Steps to Reproduce
1. Create an activity which can contain exams.
2. Edit that activity and add an exam group
3. Notice in the exam group you can set the time limit to a negative number

screen shot 2018-11-29 at 09 49 25

### PR DESCRIPTION
**Pull request by ibebic**
This resolves #138.

### CODE REVIEW

**Comment by kjuej** [comment]
@ibebic I'm able to enter "e" characters. Should we maybe disable this as well?

**Comment by ibebic** [comment]
Since `vee-validate` is not properly validating some inputs (e.g. 'e', 'ee', '2ee3', etc.) when input type is set to `number`, in order to keep the browser's increment/decrement chevrons I created a custom input element which handles those edge cases separately by using the [ValidityState](https://developer.mozilla.org/en-US/docs/Web/API/ValidityState) interface.
Errors are manually added  into the error bag and removed when cleared.

**Comment by kjuej** [comment]
@ibebic Seems to be working as expected now.

**Comment by underscope** [comment]
@abasic Try to fix it within #308

**Pull request closed without merging**
