### PR TITLE
Update tce-jodit

### PR DESCRIPTION
**Pull request by zcuric**
### This PR
- [x] Updates `tce-jodit`. It points to new `update` branch. 

### QA note
Run 
```
npm install
```

### CODE REVIEW

**Comment by bubafinder** [comment]
Looks good 👍

**Comment by underscope** [comment]
There is some flicker upon focus (placeholder showing for couple of ms)

https://user-images.githubusercontent.com/6253820/114723323-ddd01e00-9d3a-11eb-8843-758d16905dfb.mov

**Comment by zcuric** [comment]
@underscope @markolovric Flickering is addressed and should be fixed now.

**Comment by zcuric** [comment]
@underscope After closer inspection with @markolovric we concluded that we should wait until https://github.com/WendellAdriel/jodit-vue/pull/25 gets merged because the version of `jodit` that current `jodit-vue` is using is 3.4 and it's buggy as hell. After that, I will update everything again and @markolovric will do a proper deep dive QA.

**Comment by zcuric** [comment]
@markolovric tce-jodit has been updated.

**Comment by zcuric** [comment]
cc @underscope

**Pull request merged**
